#version 430

#define LOCAL_SIZE_X 0

layout(local_size_x=LOCAL_SIZE_X, local_size_y=1, local_size_z=1) in;

struct Index {
    uint boid_index;
    uint cell_index;
};

layout(std430, binding=0) buffer buffer_indices {
    Index indices[];
};

uniform uint boid_count;

void main() {
    const uint index = gl_GlobalInvocationID.x;

    if (index >= boid_count)
        return;

    indices[index].boid_index = index;
    indices[index].cell_index = 0;
}
