#version 430 core

#define LOCAL_SIZE_X 0

layout(local_size_x=LOCAL_SIZE_X, local_size_y=1, local_size_z=1) in;

#include shaders/boids/boid_struct.glsl

layout(std430, binding=0) buffer buffer_src {
    Boid boids_src[];
};

layout(std430, binding=1) buffer buffer_dst {
    Boid boids_dst[];
};

uniform uint u_boid_count;

void main() {
    const uint index = gl_GlobalInvocationID.x;

    if (index >= u_boid_count)
        return;

    boids_dst[index] = boids_src[index];
}
