def cleanup(self):
	print("Cleaning up ressources.")
	self.buffer_1.release()
	self.buffer_2.release()
	self.borders.release()
	self.compass.release()
	self.program_boids.release()
	self.boid_vertices.release()
	self.boid_color.release()
	self.vao_1.release()
	self.vao_2.release()
	self.program_border.release()
	self.program_lines.release()
